library(scatterpie)

# Input file generated by script "fte_parser.py"
df <- read.table("fte_fund_summary.txt", sep="\t", header=TRUE)

fte_df_org <- cbind(df, logTotFund=log10(df$Total_fund), logFTE=log10(df$FTE))
fte_df <- fte_df_org[-2,]

x.ticks <- c(2500, 5000, 10000, 20000, 40000)
y.ticks <- c(2.5, 5, 10, 20, 40, 80, 160)

ggplot() + geom_scatterpie(aes(x=logTotFund, y=logFTE), data=fte_df, 
                           cols=c("Scilifelab_fund", "University_fund", "Other_fund")) + coord_equal() +
    labs(fill = "") +
    scale_fill_manual(labels=c("Other funding  ", "SciLifeLab funding  ", "University funding"), values=c("#378CAF", "#80C41C", "#B1B0B1")) +
    scale_x_continuous(name="Total funding (MSEK)", breaks=log10(x.ticks), labels=x.ticks/1000, minor_breaks=NULL) +
    scale_y_continuous(name="FTE", breaks=log10(y.ticks), labels=y.ticks, minor_breaks=NULL) +   
    theme(axis.title.x = element_text(family = "Arial", size = 21),
          axis.title.y = element_text(family = "Arial", size = 21),
          axis.text.x = element_text(family = "Arial", size = 19),
          axis.text.y = element_text(family = "Arial", size = 19),
          legend.position = "top", legend.spacing = unit(1.5, "cm"),
          legend.text = element_text(family = "Arial", size = 20),
          panel.grid.major.x=element_line(color="#d6d7d8", size=0.2),
          panel.grid.minor.x=element_line(color="#d6d7d8"),
          panel.grid.major.y=element_line(color="#d6d7d8", size=0.2),
          panel.grid.minor.y=element_line(color="#d6d7d8"),
          panel.background = element_rect(fill="#FFFFFF")) 


